<?xml version="1.0"?> 
<wsdl:description xmlns:wsdl="http://www.w3.org/ns/wsdl"
	targetNamespace="http://localhost:3000/invoices"
	xmlns:tns="http://localhost:3000/invoices"
	xmlns:msg0="http://localhost:3000/invoices"
	xmlns:msg1="http://localhost:3000/invoices2"
	xmlns:whttp="http://www.w3.org/ns/wsdl/http"
	xmlns:wsdlx="http://www.w3.org/ns/wsdl-extensions">

	<wsdl:types>
		<xsd:import xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			namespace="http://localhost:3000/invoices"
			schemaLocation="http://localhost/invoice.xsd"/>
		<xsd:import xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			namespace="http://localhost:3000/invoices2"
			schemaLocation="http://localhhost/invoice2.xsd"/>
	</wsdl:types>

  <wsdl:interface name="invoiceInterface">
		<wsdl:operation name="getInvoices"
			pattern="http://www.w3.org/ns/wsdl/in-out"
			wsdlx:safe="true"
			style="http://www.w3.org/ns/wsdl/style/iri">
			<wsdl:input element="msg1:getInvoicesRequest"/>
			<wsdl:output element="msg0:getInvoicesResponse"/>
		</wsdl:operation>
	</wsdl:interface>

	<wsdl:binding name="InvoiceHTTPBinding"
		type="http://www.w3.org/ns/wsdl/http"
		interface="tns:invoiceInterface">
		<wsdl:operation ref="tns:getInvoices" whttp:method="GET"/>
  </wsdl:binding>

  <wsdl:service name="invoice" interface="tns:invoiceInterface">
		<wsdl:endpoint name="InvoiceHTTPEndpoint"
			binding="tns:InvoiceHTTPBinding"
			address="http://localhost:3000/invoices">
		</wsdl:endpoint>
	</wsdl:service>

</wsdl:description>